version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00' # UTC time
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'fix'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'security'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '09:00' # UTC time
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'fix'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'github-actions'
