name: Run Code Tests

on:
  pull_request:
    branches:
      - '**'

  workflow_dispatch:
    inputs:
      HDB_VERSION:
        description: Harper Version (latest, 4.6.1, etc)
        type: string
        required: true
        default: latest
      NODE_VERSION:
        description: Node.js Version (lts/*, 18, 20, etc)
        type: string
        required: true
        default: lts/*

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: stage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Load Node.js version
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]]; then
            source .github/config/versions.txt
            echo "NODE_VERSION=$NODE_VERSION" >> "$GITHUB_ENV"
          else
            echo "NODE_VERSION=${{ github.event.inputs.NODE_VERSION }}" >> "$GITHUB_ENV"
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        shell: bash
        run: npm install

      - name: Run unit tests
        shell: bash
        run: npm run test:unit

  check-performance-tests:
    name: Run Performance Test Checks
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check for K6 setup
        shell: bash
        run: |
          chmod +x .github/scripts/check_k6_setup.sh
          ./.github/scripts/check_k6_setup.sh tests/performance

  run-integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    env:
      CONTAINER_NAME: harperdb
      HDB_ADMIN_USERNAME: HDB_ADMIN
      HDB_ADMIN_PASSWORD: password
      HDB_DEPLOY_URL: http://localhost:9925
      HDB_OPERATIONS_URL: http://localhost:9925
      TEST_DOMAIN: https://localhost:9926
      ENVIRONMENT: integration
      MOCK_ORIGIN_HOST: host.docker.internal
      MOCK_DEFAULT_ORIGIN_PORT: 4101
      MOCK_API_ORIGIN_PORT: 4102

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Load HarperDB and Node.js versions
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]]; then
            source .github/config/versions.txt
            echo "NODE_VERSION=$NODE_VERSION" >> "$GITHUB_ENV"
            echo "HDB_VERSION=$HDB_VERSION" >> "$GITHUB_ENV"
          else
            echo "NODE_VERSION=${{ github.event.inputs.NODE_VERSION }}" >> "$GITHUB_ENV"
            echo "HDB_VERSION=${{ github.event.inputs.HDB_VERSION }}" >> "$GITHUB_ENV"
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        shell: bash
        run: npm install

      - name: Install Harper
        shell: bash
        run: |
          chmod +x .github/scripts/install_harper.sh
          ./.github/scripts/install_harper.sh $HDB_VERSION $HDB_ADMIN_USERNAME $HDB_ADMIN_PASSWORD

      - name: Start Harper Docker container
        shell: bash
        run: |
          chmod +x .github/scripts/start_harper_docker.sh
          ./.github/scripts/start_harper_docker.sh $CONTAINER_NAME $HDB_VERSION $HDB_ADMIN_USERNAME $HDB_ADMIN_PASSWORD

      - name: Build TypeScript
        shell: bash
        run: npm run build

      - name: Deploy component to Harper container
        shell: bash
        run: |
          chmod +x .github/scripts/deploy_harper_cli.sh
          ./.github/scripts/deploy_harper_cli.sh $HDB_ADMIN_USERNAME $HDB_ADMIN_PASSWORD $HDB_DEPLOY_URL $CONTAINER_NAME

      - name: Run integration tests
        shell: bash
        run: |
          set -o pipefail
          npm run test:integration 2>&1 | tee tests/integration/test-report.txt

      - name: Upload test result artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-report
          path: tests/integration/test-report.txt

      - name: Upload coverage report artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: integration-coverage
          path: coverage/
